### ISSUE TITLE
Release date

### ISSUE THREAD

**Issue by tainmar** [mgmeiner/vue-infinite-table#1]
Hey @mgmeiner,
Well played for this component, it looks great and it is really needed since no such thing exists yet.

Would you have any planned release date / publication on npmjs ?

**Comment by mgmeiner** [comment]
hey @SuperKiwi! Thanks for the feedback. I was very busy the last month so there was no progress :( but i will continue working on it.
The published version is beta but is already used in production  in my company :D. It has a few bugs and needs improvments. Are you interested in joining :)?

**Comment by tainmar** [comment]
Yes! 
I'll try to put this in production -on my side- by making some tweaks and I will eventually come back to you with some PRs

**Comment by mgmeiner** [comment]
If you like i can add you as a collaborator?

**Comment by tainmar** [comment]
Well yes I'd be pleased ;)
Thank you
